import { ApprovalListItem, approvalRequestSource, approvalStatus } from '../models/ApprovalListItem';

export const mockApprovals: ApprovalListItem[] = [{
  imageUrl: undefined,
  itemName: 'Nature Valley Crunchy Cereal Bars ',
  itemNbr: 123,
  upcNbr: 40000000123,
  categoryNbr: 1,
  categoryDescription: 'SNACKS',
  subCategoryNbr: 1,
  subCategoryDescription: '',
  newQuantity: 20,
  oldQuantity: 5,
  dollarChange: 150.50,
  initiatedUserId: 'Associate Employee',
  initiatedTimestamp: '2021-03-27T00:00:00.000Z',
  approvalStatus: approvalStatus.Pending,
  approvalRequestSource: approvalRequestSource.ItemDetails,
  isChecked: false,
  daysLeft: 3
}, {
  imageUrl: undefined,
  itemName: 'Red Apples',
  itemNbr: 456,
  upcNbr: 40000000456,
  categoryNbr: 2,
  categoryDescription: 'FRUITS/VEGETABLES',
  subCategoryNbr: 1,
  subCategoryDescription: '',
  newQuantity: 10,
  oldQuantity: 30,
  dollarChange: 50.00,
  initiatedUserId: 'Associate Worker',
  initiatedTimestamp: '2021-03-28T00:00:00.000Z',
  approvalStatus: approvalStatus.Pending,
  approvalRequestSource: approvalRequestSource.ItemDetails,
  isChecked: false,
  daysLeft: 2
}, {
  imageUrl: undefined,
  itemName: 'Cabbage',
  itemNbr: 457,
  upcNbr: 40000000457,
  categoryNbr: 2,
  categoryDescription: 'FRUITS/VEGETABLES',
  subCategoryNbr: 1,
  subCategoryDescription: '',
  newQuantity: 15,
  oldQuantity: 30,
  dollarChange: 40.00,
  initiatedUserId: 'Associate Worker',
  initiatedTimestamp: '2021-03-28T00:00:00.000Z',
  approvalStatus: approvalStatus.Pending,
  approvalRequestSource: approvalRequestSource.ItemDetails,
  isChecked: false,
  daysLeft: 2
}, {
  imageUrl: undefined,
  itemName: 'Strawberries',
  itemNbr: 458,
  upcNbr: 40000000458,
  categoryNbr: 2,
  categoryDescription: 'FRUITS/VEGETABLES',
  subCategoryNbr: 1,
  subCategoryDescription: '',
  newQuantity: 40,
  oldQuantity: 20,
  dollarChange: 80.00,
  initiatedUserId: 'Associate Worker',
  initiatedTimestamp: '2021-03-28T00:00:00.000Z',
  approvalStatus: approvalStatus.Pending,
  approvalRequestSource: approvalRequestSource.ItemDetails,
  isChecked: false,
  daysLeft: 2
}];
