import { ApprovalListItem, approvalRequestSource, approvalStatus } from '../models/ApprovalListItem';

enum CATEGORY_DESCRIPTION {
  SNACKS = 'SNACKS',
  FRUITS_VEGETABLES = 'FRUITS/VEGETABLES',
}

enum INITIATED_USER_ID {
  ASSOCIATE_EMPLOYEE = 'Associate Employee',
  ASSOCIATE_WORKER = 'Associate Worker',
}

enum INITIATED_TIMESTAMP {
  DAY1 = '2021-03-27T00:00:00.000Z',
  DAY2 = '2021-03-28T00:00:00.000Z'
}

export const mockApprovals: ApprovalListItem[] = [{
  imageUrl: undefined,
  itemName: 'Nature Valley Crunchy Cereal Bars ',
  itemNbr: 123,
  upcNbr: 40000000123,
  categoryNbr: 1,
  categoryDescription: CATEGORY_DESCRIPTION.SNACKS,
  subCategoryNbr: 1,
  subCategoryDescription: '',
  newQuantity: 20,
  oldQuantity: 5,
  dollarChange: 150.50,
  initiatedUserId: INITIATED_USER_ID.ASSOCIATE_EMPLOYEE,
  initiatedTimestamp: INITIATED_TIMESTAMP.DAY1,
  approvalStatus: approvalStatus.Pending,
  approvalRequestSource: approvalRequestSource.ItemDetails,
  isChecked: false,
  daysLeft: 3
}, {
  imageUrl: undefined,
  itemName: 'Red Apples',
  itemNbr: 456,
  upcNbr: 40000000456,
  categoryNbr: 2,
  categoryDescription: CATEGORY_DESCRIPTION.FRUITS_VEGETABLES,
  subCategoryNbr: 1,
  subCategoryDescription: '',
  newQuantity: 10,
  oldQuantity: 30,
  dollarChange: 50.00,
  initiatedUserId: 'Associate Worker',
  initiatedTimestamp: INITIATED_TIMESTAMP.DAY2,
  approvalStatus: approvalStatus.Pending,
  approvalRequestSource: approvalRequestSource.ItemDetails,
  isChecked: false,
  daysLeft: 2
}, {
  imageUrl: undefined,
  itemName: 'Cabbage',
  itemNbr: 457,
  upcNbr: 40000000457,
  categoryNbr: 2,
  categoryDescription: CATEGORY_DESCRIPTION.FRUITS_VEGETABLES,
  subCategoryNbr: 1,
  subCategoryDescription: '',
  newQuantity: 15,
  oldQuantity: 30,
  dollarChange: 40.00,
  initiatedUserId: INITIATED_USER_ID.ASSOCIATE_WORKER,
  initiatedTimestamp: INITIATED_TIMESTAMP.DAY2,
  approvalStatus: approvalStatus.Pending,
  approvalRequestSource: approvalRequestSource.ItemDetails,
  isChecked: false,
  daysLeft: 2
}, {
  imageUrl: undefined,
  itemName: 'Strawberries',
  itemNbr: 458,
  upcNbr: 40000000458,
  categoryNbr: 2,
  categoryDescription: CATEGORY_DESCRIPTION.FRUITS_VEGETABLES,
  subCategoryNbr: 1,
  subCategoryDescription: '',
  newQuantity: 40,
  oldQuantity: 20,
  dollarChange: 80.00,
  initiatedUserId: INITIATED_USER_ID.ASSOCIATE_WORKER,
  initiatedTimestamp: INITIATED_TIMESTAMP.DAY2,
  approvalStatus: approvalStatus.Pending,
  approvalRequestSource: approvalRequestSource.ItemDetails,
  isChecked: false,
  daysLeft: 2
}];

export const mockSelectedApprovals: ApprovalListItem[] = [{
  imageUrl: undefined,
  itemName: 'Nature Valley Crunchy Cereal Bars ',
  itemNbr: 123,
  upcNbr: 40000000123,
  categoryNbr: 1,
  categoryDescription: CATEGORY_DESCRIPTION.SNACKS,
  subCategoryNbr: 1,
  subCategoryDescription: '',
  newQuantity: 20,
  oldQuantity: 5,
  dollarChange: 150.50,
  initiatedUserId: INITIATED_USER_ID.ASSOCIATE_EMPLOYEE,
  initiatedTimestamp: INITIATED_TIMESTAMP.DAY1,
  approvalStatus: approvalStatus.Pending,
  approvalRequestSource: approvalRequestSource.ItemDetails,
  isChecked: true
}, {
  imageUrl: undefined,
  itemName: 'Red Apples',
  itemNbr: 456,
  upcNbr: 40000000456,
  categoryNbr: 2,
  categoryDescription: CATEGORY_DESCRIPTION.FRUITS_VEGETABLES,
  subCategoryNbr: 1,
  subCategoryDescription: '',
  newQuantity: 10,
  oldQuantity: 30,
  dollarChange: 50.00,
  initiatedUserId: INITIATED_USER_ID.ASSOCIATE_WORKER,
  initiatedTimestamp: INITIATED_TIMESTAMP.DAY1,
  approvalStatus: approvalStatus.Pending,
  approvalRequestSource: approvalRequestSource.ItemDetails,
  isChecked: true
}, {
  imageUrl: undefined,
  itemName: 'Cabbage',
  itemNbr: 457,
  upcNbr: 40000000457,
  categoryNbr: 2,
  categoryDescription: CATEGORY_DESCRIPTION.FRUITS_VEGETABLES,
  subCategoryNbr: 1,
  subCategoryDescription: '',
  newQuantity: 15,
  oldQuantity: 30,
  dollarChange: 40.00,
  initiatedUserId: INITIATED_USER_ID.ASSOCIATE_WORKER,
  initiatedTimestamp: INITIATED_TIMESTAMP.DAY2,
  approvalStatus: approvalStatus.Pending,
  approvalRequestSource: approvalRequestSource.ItemDetails,
  isChecked: true
}, {
  imageUrl: undefined,
  itemName: 'Strawberries',
  itemNbr: 458,
  upcNbr: 40000000458,
  categoryNbr: 2,
  categoryDescription: CATEGORY_DESCRIPTION.FRUITS_VEGETABLES,
  subCategoryNbr: 1,
  subCategoryDescription: '',
  newQuantity: 40,
  oldQuantity: 20,
  dollarChange: 80.00,
  initiatedUserId: INITIATED_USER_ID.ASSOCIATE_WORKER,
  initiatedTimestamp: INITIATED_TIMESTAMP.DAY2,
  approvalStatus: approvalStatus.Pending,
  approvalRequestSource: approvalRequestSource.ItemDetails,
  isChecked: true
}];
